<?
$PERM["about"]["5"]="X";
$PERM["about"]["*"]="W";
$PERM["index.php"]["5"]="X";
$PERM["about_topblock_title1.php"]["5"]="X";
$PERM["specialization"]["5"]="X";
$PERM["specialization"]["*"]="W";
$PERM["solution"]["5"]="X";
$PERM["solution"]["*"]="W";
$PERM["service"]["5"]="X";
$PERM["service"]["*"]="W";
$PERM["products"]["5"]="X";
$PERM["products"]["*"]="W";
$PERM["industrial"]["5"]="X";
$PERM["industrial"]["*"]="W";
$PERM["include"]["5"]="X";
$PERM["include"]["*"]="W";
$PERM["img"]["5"]="X";
$PERM["img"]["*"]="W";
$PERM["/"]["*"]="R";
?>